feat[添加SqlEditor与跳转上下页快捷键] 还需完善
liyupi/sql-mother pull request #13
Opened 2023-08-05 04:10 UTC by wawayes

# 添加SqlEditor与跳转上下页快捷键

星球后端选手来凑热闹，前端代码如果不够优雅还请大佬们指点。

上下翻页部分还需要完善（按钮在disabled状态下仍可通过快捷键翻页）

2023-08-05 04:18 UTC, cq2021-coder commented
格式化习惯了jetbrains家的Ctrl+Alt+L，不知道可不可以自定义快捷键🤔

2023-08-05 07:26 UTC, liyupi commented on package.json
> +    "@ant-design/icons-vue": "^6.1.0",
无需额外安装

2023-08-05 07:27 UTC, liyupi commented on src/components/QuestionBoard.vue
> +const handleKeyDown = (event: KeyboardEvent) => {
思考一下能否使用更优雅的方式实现快捷键，而不是 if else？比如引入一个独立的快捷键配置文件

2023-08-05 07:28 UTC, liyupi requested changes

2023-08-05 07:28 UTC, liyupi commented on src/components/SqlEditor.vue
> +    if (os.value === "MacOS") {
同上，思考这段代码有没有办法简化？

2023-08-05 07:28 UTC, liyupi commented on src/components/SqlEditor.vue
> +  // actions.forEach((action) => toRaw(action).dispose());
这两行的作用是？

2023-08-06 03:20 UTC, wawayes commented on src/components/QuestionBoard.vue
> +const handleKeyDown = (event: KeyboardEvent) => {
明白了屑老板 我去研究研究~

2023-08-06 03:26 UTC, closed without merging